//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinMIST2.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_AXISFORM                    102
#define IDR_GRAPHRESULTSFORMVIEW_TMPL   103
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_WINMISTYPE                  129
#define IDR_RAWMISTYPE                  130
#define IDD_RUNNING                     141
#define IDD_POLARVIEWFORM               142
#define IDD_TREEWIZARD                  145
#define IDR_TREE_MENU                   146
#define IDD_WIZARD_MAIN                 148
#define IDD_WIZARD_MODEL                149
#define IDD_WIZARD_REQUIRED             151
#define IDD_WIZARD_USER                 152
#define IDD_WIZARD_PARAM                153
#define IDD_BROWSERFORM                 155
#define IDD_WIZARDPARAMS                156
#define IDD_SAVECHANGE                  157
#define IDD_POLAROPTIONS                158
#define IDD_NEWUSERVARIABLE             159
#define IDD_NEWFORLOOP                  160
#define IDD_NEWINTEGRALDIALOG           161
#define IDD_NEWCIRCLE                   163
#define IDD_NEWPOLYGON                  167
#define IDD_CHOOSEMODEL                 169
#define IDD_NEWHEMI                     170
#define IDD_OUTPUTDIALOG                171
#define IDD_OVERWRITEWARNING            172
#define IDD_NEWDOCUMENT                 174
#define IDD_RAWMIST                     175
#define IDD_MODELVARIABLE               176
#define IDR_MODELBROWSER                177
#define IDD_NEWDIFFERENTIAL             177
#define IDD_NEWLOOPDIALOG               178
#define IDR_POLARVIEW                   179
#define IDR_GRAPHVIEW                   180
#define IDR_RESULTSVIEW                 181
#define IDR_SAMPLESVIEW                 182
#define IDR_LISTINGVIEW                 183
#define IDR_MENU1                       184
#define IDD_LISTLOOPDIALOG              187
#define IDD_NEWSEHEMI                   188
#define IDD_NEWANNULUS                  189
#define IDC_XAxisCombo                  1001
#define IDC_YAxisCombo                  1002
#define IDC_XLOG                        1011
#define IDC_YLOG                        1012
#define IDC_PROGRESS1                   1012
#define IDC_SLIDER1                     1015
#define IDC_SLIDER2                     1016
#define IDC_BUTTON1                     1017
#define IDC_BUTTON2                     1018
#define IDC_OPTIONS                     1018
#define IDC_MOVEDOWN                    1018
#define IDC_BUTTON3                     1019
#define IDC_BUTTON4                     1020
#define IDC_BUTTON5                     1021
#define IDC_TREE1                       1028
#define IDC_WMODEL                      1038
#define IDC_WVARREQ                     1039
#define IDC_COMBO1                      1039
#define IDC_COMBO                       1039
#define IDC_WVARUSER                    1040
#define IDC_EDIT1                       1040
#define IDC_WVARMODEL                   1041
#define IDC_EDIT2                       1041
#define IDC_LIST1                       1041
#define IDC_WINTEGRAL                   1042
#define IDC_EDIT3                       1042
#define IDC_SHOWINTENSITY               1042
#define IDC_WOUTPUTS                    1043
#define IDC_EDIT4                       1043
#define IDC_AUTOSCALE                   1043
#define IDC_SHOWBRDF                    1043
#define IDC_WVARY                       1044
#define IDC_INVERTSCALE                 1044
#define IDC_WFILES                      1045
#define IDC_POLARMIN                    1045
#define IDC_POLARMAX                    1046
#define IDC_MODELNAME                   1047
#define IDC_CREATEMODEL                 1048
#define IDC_TEXT                        1049
#define IDC_APPLY                       1050
#define IDC_TREE                        1051
#define IDC_SPIN2                       1053
#define IDC_ORDER                       1054
#define IDC_ADD                         1055
#define IDC_REMOVE                      1056
#define IDC_TO                          1058
#define IDC_BY                          1059
#define IDC_FROM                        1060
#define IDC_VARIABLE                    1061
#define IDC_POLARIZATION                1066
#define IDC_VERTICES                    1068
#define IDC_THETA                       1069
#define IDC_PHI                         1070
#define IDC_POL                         1071
#define IDC_ADDVERTEX                   1072
#define IDC_DELETE                      1073
#define IDC_EDIT                        1074
#define IDC_DESCRIPTION                 1075
#define IDC_NAME                        1076
#define IDC_CREATERAWMIST               1078
#define IDC_MOVEUP                      1079
#define IDC_ALWAYSAUTOSCALE             1080
#define IDC_FIXZERO                     1081
#define IDC_STRING                      1086
#define IDC_POLAR                       1091
#define IDC_AZIMUTH                     1092
#define IDC_COMMENT                     1093
#define IDC_LABEL                       1094
#define IDC_COMMENT2                    1094
#define IDC_INCPOL                      1095
#define IDC_FOR                         1096
#define IDC_HEMI                        1097
#define IDC_CIRCLE                      1098
#define IDC_POLYGON                     1099
#define IDC_DIFFERENTIAL                1100
#define IDC_LIST                        1101
#define IDC_SEHEMI                      1101
#define IDC_ANNULUS                     1101
#define IDC_BROWSE                      1102
#define IDC_ALPHA                       1103
#define IDC_AZIMUTHAL                   1104
#define IDC_EDIT6                       1105
#define IDC_OUTERALPHA                  1105
#define IDC_INNERPOLAR                  1106
#define IDC_INNERAZIMUTHAL              1107
#define IDC_INNERALPHA                  1108
#define IDC_OUTERPOLAR                  1109
#define IDC_OUTERAZIMUTHAL              1110
#define IDC_CHECK1                      1113
#define ID_VIEW_RESULTS_TEXT            32771
#define ID_VIEW_RESULTS_GRAPH           32772
#define ID_VIEW_LISTING                 32773
#define ID_VIEW_SAMPLES_TEXT            32774
#define ID_VIEW_SAMPLES_GRAPH           32775
#define ID_CALCULATE                    32776
#define ID_SIMULATE                     32777
#define ID_BUTTON32780                  32780
#define ID_TREE_NEW                     32783
#define ID_TREE_EDIT                    32784
#define ID_TREE_DELETE                  32785
#define ID_WIZARD                       32786
#define ID_MODELWIZARD                  32788
#define ID_ADD                          32789
#define ID_REMOVE                       32790
#define ID_VIEWRAW                      32794
#define ID_ENTER                        32795
#define ID_HELP_MISTWEB                 32798
#define ID_HELP_SCATMECHWEB             32799
#define ID_EDIT                         32800
#define ID_DELETE                       32801
#define ID_PURGE                        32803
#define ID_MIST0                        65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
